name: crypto_currency
description: Crypto currency app using CLEAN architecture using GetX as state management

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_secure_storage: ^8.0.0
  get: ^4.6.5
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  share_plus: ^7.1.0
  connectivity_plus: ^4.0.2
  flutter_spinkit: ^5.2.0
  ionicons: ^0.2.2
  flutter_screenutil: ^5.8.4
  dartz: ^0.10.1
  logger: ^2.0.1
  flutter_svg: ^2.0.7
  delayed_widget: ^1.1.2
  mockito: ^5.4.2
  local_auth: ^2.1.6
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/general/

  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins.ttf